name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
# 如果想要手动为 CUSTOM_DOMAIN 添加 DNS 解析记录，请注释或删除掉 route
routes = [
  { pattern = "hub.hczhch.dpdns.org", custom_domain = true },
  { pattern = "docker.hczhch.dpdns.org", custom_domain = true },
  { pattern = "quay.hczhch.dpdns.org", custom_domain = true },
  { pattern = "gcr.hczhch.dpdns.org", custom_domain = true },
  { pattern = "k8s-gcr.hczhch.dpdns.org", custom_domain = true },
  { pattern = "k8s.hczhch.dpdns.org", custom_domain = true },
  { pattern = "ghcr.hczhch.dpdns.org", custom_domain = true },
  { pattern = "cloudsmith.hczhch.dpdns.org", custom_domain = true },
  { pattern = "ecr.hczhch.dpdns.org", custom_domain = true },
  { pattern = "mcr.hczhch.dpdns.org", custom_domain = true },
  { pattern = "elastic.hczhch.dpdns.org", custom_domain = true },
  { pattern = "nvcr.hczhch.dpdns.org", custom_domain = true },
  { pattern = "juju.hczhch.dpdns.org", custom_domain = true },
  { pattern = "l5d.hczhch.dpdns.org", custom_domain = true },
  { pattern = "rocks.hczhch.dpdns.org", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
